SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_ALL_TABLES';


CREATE DATABASE IF NOT EXISTS zayon_uan CHARACTER SET = 'utf8mb4' COLLATE = 'utf8mb4_unicode_ci';
USE zayon_uan;


CREATE TABLE IF NOT EXISTS ingredientes (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  descricao VARCHAR(255) NOT NULL,
  unidade_medida VARCHAR(50) DEFAULT NULL,
  custo DECIMAL(10,2) DEFAULT 0.00,
  porcao_individual DECIMAL(10,2) DEFAULT NULL,
  quantidade_estoque DECIMAL(12,2) DEFAULT 0.00,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS fornecedores (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  razao_social VARCHAR(255) DEFAULT NULL,
  nome_fantasia VARCHAR(255) DEFAULT NULL,
  cnpj VARCHAR(32) DEFAULT NULL,
  inscricao_estadual VARCHAR(64) DEFAULT NULL,
  telefone VARCHAR(64) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY idx_fornecedor_cnpj (cnpj)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS receitas (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  nome_receita VARCHAR(255) NOT NULL,
  classificacao_custo VARCHAR(100) DEFAULT NULL,
  modo_preparo TEXT DEFAULT NULL,
  producao VARCHAR(100) DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS receita_ingredientes (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  receita_id INT UNSIGNED NOT NULL,
  ingrediente_id INT UNSIGNED NOT NULL,
  quantidade DECIMAL(12,4) DEFAULT NULL,
  unidade_medida VARCHAR(50) DEFAULT NULL,
  custo DECIMAL(10,2) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_receita (receita_id),
  KEY idx_ingrediente (ingrediente_id),
  CONSTRAINT fk_receita_ingrediente_receita FOREIGN KEY (receita_id) REFERENCES receitas(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_receita_ingrediente_ingrediente FOREIGN KEY (ingrediente_id) REFERENCES ingredientes(id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS cardapios (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  dia_semana VARCHAR(32) DEFAULT NULL,
  data DATE DEFAULT NULL,
  descricao TEXT DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS cardapios_refeicoes (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  cardapio_id INT UNSIGNED DEFAULT NULL,
  tipo_refeicao VARCHAR(100) DEFAULT NULL,
  receita_id INT UNSIGNED DEFAULT NULL,
  descricao TEXT DEFAULT NULL,
  data DATE DEFAULT NULL,
  arranchamento VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_cardapio (cardapio_id),
  KEY idx_receita_ref (receita_id),
  CONSTRAINT fk_cardapio_ref_cardapio FOREIGN KEY (cardapio_id) REFERENCES cardapios(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_cardapio_ref_receita FOREIGN KEY (receita_id) REFERENCES receitas(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS cotacoes (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  cnpj VARCHAR(32) DEFAULT NULL,
  razao_social VARCHAR(255) DEFAULT NULL,
  telefone VARCHAR(64) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS cotacao_itens (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  cotacao_id INT UNSIGNED NOT NULL,
  descricao TEXT NOT NULL,
  unidade VARCHAR(50) DEFAULT NULL,
  preco DECIMAL(12,4) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_cotacao (cotacao_id),
  CONSTRAINT fk_cotacao_itens_cotacao FOREIGN KEY (cotacao_id) REFERENCES cotacoes(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS refeicao_itens (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  refeicao_id INT UNSIGNED DEFAULT NULL,
  item_tipo VARCHAR(64) DEFAULT NULL,
  item_id INT UNSIGNED DEFAULT NULL,
  quantidade DECIMAL(12,4) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_refeicao (refeicao_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

